version: "3"

services:
  db:
    build: ./mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
  client:
    build: ./client
    ports:
      - 8080:8080
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - 8081:8081
    depends_on:
      - db